content = open("app/services/voice.py", "r", encoding="utf-8").read()

# 1. Add is_elevenlabs_voice after is_mimo_voice
old1 = "def is_mimo_voice(voice_name: str):\n    \"\"\"\u68c0\u67e5\u662f\u5426\u662f Xiaomi MiMo TTS \u7684\u58f0\u97f3\"\"\"\n    return voice_name.startswith(\"mimo:\")"
new1 = old1 + '\n\n\ndef is_elevenlabs_voice(voice_name: str):\n    """\u68c0\u67e5\u662f\u5426\u662f ElevenLabs TTS \u7684\u58f0\u97f3"""\n    return voice_name.startswith("elevenlabs:")'
content = content.replace(old1, new1)

# 2. Add routing in tts() before final return
old2 = "    elif is_mimo_voice(voice_name):\n        # \u4ecevoice_name\u4e2d\u63d0\u53d6\u58f0\u97f3\u540d\u79f0\n        # \u683c\u5f0f: mimo:voice-Gender\uff1b\u5982\u679c\u8c03\u7528\u65b9\u5df2\u6267\u884c parse_voice_name\uff0c\n        # \u5219\u53ef\u80fd\u662f mimo:voice\u3002\u4e24\u79cd\u683c\u5f0f\u90fd\u517c\u5bb9\u3002\n        parts = voice_name.split(\":\")\n        if len(parts) >= 2:\n            voice_with_gender = parts[1]\n            voice = voice_with_gender.split(\"-\")[0]\n            return mimo_tts(text, voice, voice_rate, voice_file, voice_volume)\n        else:\n            logger.error(f\"Invalid mimo voice name format: {voice_name}\")\n            return None\n    return azure_tts_v1(text, voice_name, voice_rate, voice_file)"
new2 = '    elif is_mimo_voice(voice_name):\n        # \u4ecevoice_name\u4e2d\u63d0\u53d6\u58f0\u97f3\u540d\u79f0\n        # \u683c\u5f0f: mimo:voice-Gender\uff1b\u5982\u679c\u8c03\u7528\u65b9\u5df2\u6267\u884c parse_voice_name\uff0c\n        # \u5219\u53ef\u80fd\u662f mimo:voice\u3002\u4e24\u79cd\u683c\u5f0f\u90fd\u517c\u5bb9\u3002\n        parts = voice_name.split(":")\n        if len(parts) >= 2:\n            voice_with_gender = parts[1]\n            voice = voice_with_gender.split("-")[0]\n            return mimo_tts(text, voice, voice_rate, voice_file, voice_volume)\n        else:\n            logger.error(f"Invalid mimo voice name format: {voice_name}")\n            return None\n    elif is_elevenlabs_voice(voice_name):\n        # Format: elevenlabs:voice_id ho\u1eb7c elevenlabs:voice_id-VoiceName-Gender\n        parts = voice_name.split(":")\n        if len(parts) >= 2:\n            voice_with_gender = parts[1]\n            voice_id = voice_with_gender.split("-")[0]\n            return elevenlabs_tts(text, voice_id, voice_rate, voice_file, voice_volume)\n        else:\n            logger.error(f"Invalid elevenlabs voice name format: {voice_name}")\n            return None\n    return azure_tts_v1(text, voice_name, voice_rate, voice_file)'
content = content.replace(old2, new2)

# 3. Add get_elevenlabs_voices after get_mimo_voices  
old3 = '    return [f"mimo:{voice}-{gender}" for voice, gender in voices_with_gender]\n\n_AZURE_VOICES_DATA_FILE'
new3 = '    return [f"mimo:{voice}-{gender}" for voice, gender in voices_with_gender]\n\n\ndef get_elevenlabs_voices() -> list[str]:\n    """\n    Get ElevenLabs TTS voice list.\n    If API key is configured, fetch from API. Otherwise return common voices.\n    \n    Returns:\n        List of voices in format "elevenlabs:voice_id-VoiceName-Gender"\n    """\n    api_key = config.app.get("elevenlabs_api_key", "")\n    if api_key:\n        try:\n            from elevenlabs.client import ElevenLabs\n            client = ElevenLabs(api_key=api_key)\n            response = client.voices.search()\n            voices = []\n            for v in response.voices:\n                gender = getattr(v, "gender", "Unknown") or "Unknown"\n                voices.append(f"elevenlabs:{v.voice_id}-{v.name}-{gender}")\n            if voices:\n                return sorted(voices)\n        except Exception as e:\n            logger.warning(f"Failed to fetch ElevenLabs voices: {str(e)}")\n\n    # Fallback: common ElevenLabs voices\n    common_voices = [\n        ("JBFqnCBsd6RMkjVDRZzb", "Rachel", "Female"),\n        ("21m00Tcm4TlvDq8ikWAM", "Adam", "Male"),\n        ("ODq5zmih8GrVes37Dizd", "Patrick", "Male"),\n        ("EXAVITQu4vr2nSDke1cM", "Elli", "Female"),\n        ("XrExE9yKIg1WjnnlV5kG", "Aria", "Female"),\n        ("N2lVS1w4EtoT3dr4rgOW", "Domi", "Female"),\n        ("IKne3meq5aSn9XLyUdCD", "Oliver", "Male"),\n        ("onwK4e9ZLuTAKqWW03F9", "Daniel", "Male"),\n        ("pMsXgVXv3BLzUg7XRGFv", "Bella", "Female"),\n        ("LcfcDJNUP1GQjkzn1xUU", "Emily", "Female"),\n        ("Yj8o4eOVY0jDn2AdSW1J", "Chris", "Male"),\n        ("z9fAnlkpzviPz146aGWa", "Brian", "Male"),\n        ("5Q0t7uMcjvn0Fv1VArQX", "Antoni", "Male"),\n        ("ThT5KcBeYPX3keUQqHPh", "Dorothy", "Female"),\n    ]\n    return [\n        f"elevenlabs:{voice_id}-{name}-{gender}"\n        for voice_id, name, gender in common_voices\n    ]\n\n_AZURE_VOICES_DATA_FILE'
content = content.replace(old3, new3)

open("app/services/voice.py", "w", encoding="utf-8").write(content)
print("voice.py patched")
